### ISSUE TITLE
Facing error while establishing connection to druid setup

### ISSUE THREAD

**Issue by Vamsi-DISYS** [Zenysis/Harmony#103]
harmony-dev-web-1       | 
harmony-dev-web-1       | During handling of the above exception, another exception occurred:
harmony-dev-web-1       | 
harmony-dev-web-1       | 
harmony-dev-web-1       | Traceback (most recent call last):
harmony-dev-web-1       |   File "/app/web/runserver.py", line 94, in <module>
harmony-dev-web-1       |     sys.exit(main())
harmony-dev-web-1       |   File "/app/web/runserver.py", line 89, in main
harmony-dev-web-1       |     app = create_app(flask_config, instance_config, environment)
harmony-dev-web-1       |   File "/app/web/server/app.py", line 455, in create_app
harmony-dev-web-1       |     app = _create_app_internal(flask_config, instance_config, configuration_module)
harmony-dev-web-1       |   File "/app/web/server/app.py", line 186, in _create_app_internal
harmony-dev-web-1       |     _initialize_druid_context(app)
harmony-dev-web-1       |   File "/app/web/server/app.py", line 253, in _initialize_druid_context
harmony-dev-web-1       |     if datasource_config in druid_metadata.get_datasources_for_site(deployment_name):
harmony-dev-web-1       |   File "/app/db/druid/metadata.py", line 98, in get_datasources_for_site
harmony-dev-web-1       |     return [ds.name for ds in self.get_site_datasources() if ds.site == site]
harmony-dev-web-1       |   File "/app/db/druid/metadata.py", line 91, in get_site_datasources
harmony-dev-web-1       |     for ds in self.get_all_datasources()
harmony-dev-web-1       |   File "/app/db/druid/metadata.py", line 81, in get_all_datasources
harmony-dev-web-1       |     r = requests.get(url)
harmony-dev-web-1       |   File "/app/venv/lib/python3.9/site-packages/requests/api.py", line 73, in get
harmony-dev-web-1       |     return request("get", url, params=params, **kwargs)
harmony-dev-web-1       |   File "/app/venv/lib/python3.9/site-packages/requests/api.py", line 59, in request
harmony-dev-web-1       |     return session.request(method=method, url=url, **kwargs)
harmony-dev-web-1       |   File "/app/venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
harmony-dev-web-1       |     resp = self.send(prep, **send_kwargs)
harmony-dev-web-1       |   File "/app/venv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
harmony-dev-web-1       |     r = adapter.send(request, **kwargs)
harmony-dev-web-1       |   File "/app/venv/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
harmony-dev-web-1       |     raise ConnectionError(e, request=request)
harmony-dev-web-1       | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /druid/coordinator/v1/metadata/datasources (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f997d294790>: Failed to establish a new connection: [Errno 111] Connection refused'))
harmony-dev-web-1       | error Command failed with exit code 1.
harmony-dev-web-1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
harmony-dev-hasura-1    | {"detail":"Stopping immortal processScheduledTriggers thread","level":"info","timestamp":"2023-08-01T15:02:51.008+0000","type":"unstructured"}
harmony-dev-web-1 exited with code 1

The above is the error I'm facing while executing the docker compose up command. It is failing to establish connection to the druid setup and also what is the hostname of the druid host which is to be mentioned in the .env file

**Comment by Sybrand** [comment]
@Vamsi-DISYS you need to have a working druid instance, with a datasource matching the `ZEN_ENV`. You would then configure your environment to point to the druid instance.

You could get druid running locally - but I would point you to https://druid.apache.org/ for that. If you're feeling very adventurous you can try the sample druid configurations in `druid_setup` ; but you may have mixed success depending on what hardware you're running, and your familiarity with the ins and outs of docker.
